### ISSUE TITLE
Move table to another tablespace while repacking

### ISSUE THREAD

**Issue by andreasscherbaum** [adjust/pg_repack#2]
The "new" repacked table can be moved to another tablespace during the operation.

Idea from @nick-adjust 

Let's discuss how to configure this properly.

@za-arthur Please add your comments.

**Comment by nick-adjust** [comment]
This shall be implemented [here instead.](https://github.com/adjust/db_jobs/blob/master/shards/scripts/repack.sh#L59)
We need to have a separate run that deals explicitly with moving _old_ **non-cohort** partitions from `ssd` tablespace to default tablespace.

**Comment by za-arthur** [comment]
Can we close this issue? It was solved within another issue.
