### ISSUE TITLE
Check how far behind the extension is with regards to upstream

### ISSUE THREAD

**Issue by andreasscherbaum** [adjust/pg_repack#4]
Do we have any outstanding patches which are in upstream but not in our fork?
Can they easily be merged?

Don't start merging right now, list the open issues here please.

**Comment by za-arthur** [comment]
I checked this. And it seems that our repository contains some code which adds Postgres 12 support. Probably at that time upstream `pg_repack` didn't have Postgres 12 support.

Other than that there are no much differences actually:
- Upstream `pg_repack` supports PostgreSQL 9.4, 9.5, 9.6, 10, 11, 12, 13; has updated links, copyright years.
- Adjust `pg_repack` supports PostgreSQL 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 10, 11, 12.

As a conclusion, when we start using Postgres 13+ we can just start using upstream `pg_repack`.

**Comment by andreasscherbaum** [comment]
We have to merge changes from upstream, since our current version is not supporting PG 13.

**Comment by za-arthur** [comment]
I think we can start building upstream repository instead of maintaining our own repository.
As I mentioned [above](https://github.com/adjust/pg_repack/issues/4#issuecomment-793703727) our repository has different code for Postgres 12 support.
Our `pg_repack` supports PostgreSQL 9.1, 9.2, 9.3 but we don't have such old versions of Postgres in our servers.
So I don't see a reason to maintain our own repository.

**Comment by andreasscherbaum** [comment]
@za-arthur Is there any code which requires to use our fork? Or is our fork obsolete?

**Comment by za-arthur** [comment]
As I wrote above:
> And it seems that our repository contains some code which adds Postgres 12 support. Probably at that time upstream pg_repack didn't have Postgres 12 support.

I checked this using `git diff` between ours master and upstream's master. Upon support of different PostgreSQL version there are other difference:
- Different copyright years
- Links (like download and homepage links) use `https` instead of `http`
- Different homepage links

**Comment by andreasscherbaum** [comment]
Therefore no functional differences.

At some point we can - and should - switch over to upstream, and stop doing our own fork.
However when we do this, we should uninstall it everywhere and reinstall upstream.

**Comment by za-arthur** [comment]
Actually I think it is better to have our own fork. With our fork we can implement a fix faster. See for example:
https://adjustcom.atlassian.net/browse/PAD-234

I'll merge changes from upstream to our fork soon.

**Comment by za-arthur** [comment]
Created a PR to merge upstream changes https://github.com/adjust/pg_repack/pull/10
