### ISSUE TITLE
Extension does not work with PG 13

### ISSUE THREAD

**Issue by andreasscherbaum** [adjust/pg_repack#5]
The extension does not compile on PG 13:
```
ERROR:  could not load library "/usr/lib/postgresql/13/lib/pg_repack.so": /usr/lib/postgresql/13/lib/pg_repack.so: undefined symbol: heap_open
```
A couple symbols are updated in 13, upstream already has this fixed.
One more reason to move forward with #4.

**Comment by za-arthur** [comment]
I merged upstream changes. See PR https://github.com/adjust/pg_repack/pull/7
